### ISSUE TITLE
[REFACTOR] 메인뷰 리펙토링 및 수정

### ISSUE THREAD

**Issue by ho-taek** [TeamChaRo/ChaRo-Android#80]
## 🚗 제목

메인뷰 리펙토링 및 수정

## 🚕 할일

- [x] 스플래시 1초 빠르게 조정

- [ ] 드라이브 코스 띄우는 뷰 MVVM 패턴으로 변경

- [ ] layout 간격 다시 조정

- [ ] 드라이브 코스가 배너 밑으로 안들어가게 조정

**Comment by hansh0101** [comment]
MVVM OH !!!!
