### ISSUE TITLE
[REFACTOR] WriteView : Activity -> Fragment 변환

### ISSUE THREAD

**Issue by HJinhee** [TeamChaRo/ChaRo-Android#94]
## 🚗 제목
작성하기 뷰 : activity > fragment 변환
화면 이동 간의 데이터 전달 문제 해결을 위함

## 🚕 할일
- [x] SharedViewModel 학습 후 적용
- [x] activity > fragment 변환

**Comment by hansh0101** [comment]
멋져요 선생님 ~
